### ISSUE TITLE
Rename textbin 

### ISSUE THREAD

**Issue by C-o-m-o-n** [Comon-tech/Pytextbin#9]
Hello @r0ld3x , @Tinny-Robot , @PB2204 , @LyubomirT , hope you are doing well, 
I have issues with my Pypi account so I'll have to create a new one in order to publish textbin. 
However, I won't be able to use the same name. As the contributors, I'd love it if you help
me coin a new name for the package. Feel free to share your thoughts and we will all
vote to select one. Thanks

**Comment by LyubomirT** [comment]
Sure! I'll try to come up with something. Will tell you my thoughts after I finish my history exam.

**Comment by C-o-m-o-n** [comment]
No worries @LyubomirT

**Comment by r0ld3x** [comment]
> Hello @r0ld3x , @Tinny-Robot , @PB2204 , @LyubomirT , hope you are doing well, 
> I have issues with my Pypi account so I'll have to create a new one in order to publish textbin. 
> However, I won't be able to use the same name. As the contributors, I'd love it if you help
> me coin a new name for the package. Feel free to share your thoughts and we will all
> vote to select one. Thanks 

Do your best bro. Btw how you can't use same same?

**Comment by C-o-m-o-n** [comment]
> > Hello @r0ld3x , @Tinny-Robot , @PB2204 , @LyubomirT , hope you are doing well,
> > I have issues with my Pypi account so I'll have to create a new one in order to publish textbin.
> > However, I won't be able to use the same name. As the contributors, I'd love it if you help
> > me coin a new name for the package. Feel free to share your thoughts and we will all
> > vote to select one. Thanks
> 
> Do your best bro. Btw how you can't use same same?

yah, I don't even think you are able to rename a package in Pypi

**Comment by r0ld3x** [comment]
> > > Hello @r0ld3x , @Tinny-Robot , @PB2204 , @LyubomirT , hope you are doing well,
> > > I have issues with my Pypi account so I'll have to create a new one in order to publish textbin.
> > > However, I won't be able to use the same name. As the contributors, I'd love it if you help
> > > me coin a new name for the package. Feel free to share your thoughts and we will all
> > > vote to select one. Thanks
> > 
> > 
> > Do your best bro. Btw how you can't use same same?
> 
> yah, I don't even think you are able to rename a package in Pypi

make it like pytextbin or similar like that

**Comment by C-o-m-o-n** [comment]
That's a good one. Let's see if the others agree with it

**Comment by r0ld3x** [comment]
> That's a good one. Let's see if the others agree with it

sure :)

**Comment by LyubomirT** [comment]
> > > > Hello @r0ld3x , @Tinny-Robot , @PB2204 , @LyubomirT , hope you are doing well,
> > > > I have issues with my Pypi account so I'll have to create a new one in order to publish textbin.
> > > > However, I won't be able to use the same name. As the contributors, I'd love it if you help
> > > > me coin a new name for the package. Feel free to share your thoughts and we will all
> > > > vote to select one. Thanks
> > > 
> > > 
> > > Do your best bro. Btw how you can't use same same?
> > 
> > yah, I don't even think you are able to rename a package in Pypi
> 
> make it like pytextbin or similar like that 
> 

Good idea. Either `pytextbin`, `textbinpy`, or `textbin-python` should do. The last decision depends on the choice of @C-o-m-o-n, though.

**Comment by r0ld3x** [comment]
> > > > > Hello @r0ld3x , @Tinny-Robot , @PB2204 , @LyubomirT , hope you are doing well,
> > > > > I have issues with my Pypi account so I'll have to create a new one in order to publish textbin.
> > > > > However, I won't be able to use the same name. As the contributors, I'd love it if you help
> > > > > me coin a new name for the package. Feel free to share your thoughts and we will all
> > > > > vote to select one. Thanks
> > > > 
> > > > 
> > > > Do your best bro. Btw how you can't use same same?
> > > 
> > > yah, I don't even think you are able to rename a package in Pypi
> > 
> > make it like pytextbin or similar like that 
> > 
> 
> Good idea. Either `pytextbin`, `textbinpy`, or `textbin-python` should do. The last decision depends on the choice of @C-o-m-o-n, though.

Yes

**Comment by PB2204** [comment]
Hello guys !!! @r0ld3x , @C-o-m-o-n , @LyubomirT , @Tinny-Robot hope you're doing really well. You can rename the #textbin pypi project to one of the name proposed by @LyubomirT . To change the name of a pypi project we should follow some steps ,-

1) Create a renamed version of the package.
2) Publish it to PyPI under the new name.
3) Create a final release under the old name which tells users about the name change.

**Comment by C-o-m-o-n** [comment]
I like `pythextbin` I'm' choosing that, we'll get @Tinny-Robot to speed on this. Thanks guys

**Comment by C-o-m-o-n** [comment]
renamed and published
